for i in range (10):
    for j in range (10):
        print ( i ," x ", j, " = ", i + j)
    print ("_________________________")
    
    #OBS E QUANTO A VARIÁVEL FOR IGUAL A 1 ELE VAI RODAR DEZ VEZES FAZENDO ASSIM QUE ELA FAÇA UMA TABUADA DE 1 ATE 9 POIS O VALOR COLOCADO FOI 10 ENTÃO CE SAI 9 CASO EU QUERIA 10 EXATO EU POSSO POR 11 ASSIM ELE CRIARA A CONTA DE 1 ATE 10. 
    
    #OBS O PRIMEIRO FOR SERA O NÚMERO DO LADO DIREITO, JA O SEGUNDO FOR SERA O DO LADO ESQUERDO 